# codex environment for Gymnasium + MuJoCo + Box2D on HiPerGator
# CUDA 12.8 is provided by the system; no cudatoolkit here.
name: codex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - swig>=4.3
  - numpy=2.2.6
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - matplotlib=3.10.6
  - pillow
  - imageio
  - box2d-py=2.3.5      # prebuilt; removes SWIG-before-Box2D constraint
  - jupyterlab
  - ipykernel
  # minimal GL/EGL runtime pieces useful on headless nodes
  - libglvnd
  - libgl
  - libegl
  - libvulkan-loader
  - xorg-libx11
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxxf86vm
  - xorg-libxfixes
  - xorg-libxi
  - pip:
      - "gymnasium[mujoco]==1.2.1"
      - mujoco==3.3.6
      - glfw==2.10.0
      - pygame==2.6.1
      - PyOpenGL==3.1.10
      - cloudpickle==3.1.1
      - farama-notifications==0.0.4
